#!/usr/bin/env bash

set -e

if [ $# -ne 1 ] || [ ! -r "$1" ] ; then
    exit 1
fi

/opt/mozjpeg/bin/jpegtran -optimize -progressive -copy none -outfile "$1.new" "$1"

oldSize="$(ls -l $1 | awk '{print $5}')"
newSize="$(ls -l $1.new | awk '{print $5}')"

echo "Old size: $oldSize, new size $newSize"

if [ "$oldSize" -gt "$newSize" ]; then
    echo "Use new one to overwrite origin"
    mv "$1.new" "$1"
else
    echo "Drop the new one"
    rm "$1.new"
fi
